spring:  
  profiles:  
    active: dev 
---  
spring:  
  profiles: dev
  rabbitmq:
    host: 172.16.36.80
    port: 5672
    username: guest
    password: guest
    virtual-host1: /msgbus1
    virtual-host2: /msgbus2
    enable: true
server:
  port: 8090


