spring:  
  profiles:  
    active: dev 
---  
spring:  
  profiles: dev
server:
  port: 8090
logging:
  level:
    tk:
      mybatis: TRACE
  rabbitmq:
    host: 10.18.19.64
    port: 5674
    username: admin
    password: dangerous
    virtual-host: /msgbus
    enable: true
